### ISSUE TITLE
Specifying a local model

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#10]
I really like the download model feature that oobabooga uses and wanted to test out linking directly to another model using your model_path and checkpoint_path in the config.  However, I can't seem to get it to work.  I downloaded TheBloke 13b model via the oobabooga download and linked to the directory and the file using the config variables but i get this error:

learn-langchain\gptq_for_llama\quant\quant_linear.py", line 267, in matmul248
    matmul_248_kernel[grid](input, qweight, output, scales, qzeros, g_idx, input.shape[0], qweight.shape[1], input.shape[1], bits, maxq, input.stride(0), input.stride(1), qweight.stride(0),   
NameError: name 'matmul_248_kernel' is not defined

I honestly find all of these "model" files super confusing.  There are safetensors files, bin files, .pt files.  It's a real mess.  Do you have any help or tips here?  Could you provide an example of linking to a local model file?  I think what happens by default is that your code is using the cached hugging face model download.

**Comment by paolorechia** [comment]
Hey, it’s very likely that the local model is broken for quantized ones, as I’ve never tested this specific combination.

Or does it also not work with standard unquantized HF models?

It could also be that the whole local model loading is broken, as I stopped using it in the last days to setup the quantized version.

Another thing to keep in mind, is that my code assumes the quant model uses group size 128.

**Comment by paolorechia** [comment]
Also, can you share which 13b model exactly you downloaded? I could try it out on my end

**Comment by paolorechia** [comment]
1. Loading quant model should now work, fixed a bug there - here's an example I've added to the repo: https://github.com/paolorechia/learn-langchain/blob/main/run_server.sh

2. Keep in mind this only works for group_size=128, if you need support for other models, send me the model link.

3. Another thing to keep in mind: if you're running in the same terminal session, the environment variables from previous runs might be conflicting, if things get weird, start a new session or call something like `unset MODEL_PATH` (or the equivalent in Windows terminal).

Regarding your questions:

> I honestly find all of these "model" files super confusing. There are safetensors files, bin files, .pt files. It's a real mess. Do you have any help or tips here? Could you provide an example of linking to a local model file? I think what happens by default is that your code is using the cached hugging face model download.

1. Safetensor is the newer format supported by GPTQ-For-LLama, does not work in all GPUs apparently.
2. `.pt` is just a regular pytorch model, also used by older verisons of the GPTQ-For-LLama library.
3. The `bin` files I believe are used by the Hugging Face format.

**Comment by paolorechia** [comment]
This may be related to https://github.com/paolorechia/learn-langchain/issues/9

I've partially implemented something to help with this, the `requirements.txt` now point to a fork of GPTQ-For-Llama, instead of a local directory copy: 

`gptq-for-llama @ git+https://github.com/paolorechia/GPTQ-for-LLaMa@cadbacf0dcc18f7c56db54561ad53ba0f8db878c`

One way I think to address this is to create a fork too of the older, compatible oobabooga fork, and then change this line in the requirements to use the compatible version of the library.

The forked version must be modified to include a `setup.py`, plus a few code changes, like I did my GPTQ-For-LLama fork.


I might be able to implement it sometime in the future - I'm not planning more coding for the next days. Any chances you would be able to fork it yourself?
