### ISSUE TITLE
Linux install, No module named 'gptq_for_llama'

### ISSUE THREAD

**Issue by unoriginalscreenname** [paolorechia/learn-langchain#22]
I finally gave up on windows and installed everything on a fresh ubuntu wsl.  I have everything setup properly including the nvidia toolkit, however if you try and run the server with 4 bit true, you get this error:

from gptq_for_llama.llama_inference import load_quant
ModuleNotFoundError: No module named 'gptq_for_llama'

**Comment by paolorechia** [comment]
Did you install this package already?

gptq-for-llama @ git+https://github.com/paolorechia/GPTQ-for-LLaMa@cadbacf0dcc18f7c56db54561ad53ba0f8db878c

**Comment by paolorechia** [comment]
It’s in the requirements.txt

**Comment by paolorechia** [comment]
Sorry to hear about the bad experience - I’m using Ubuntu personally ,
hadn’t had that many problems

It looks like you might need to debug your environment - maybe also delete
everything and try again

Another thing you can try is cloning the GPTQ-For-Llama repo and installing
it locally

You can enter the directory and do
pip install -e .




TestUser ***@***.***> schrieb am So. 7. Mai 2023 um 12:41:

**Comment by paolorechia** [comment]
Nice to hear, I’ll keep this issue open since more people might run into this issue

**Comment by SunnyBingoMe** [comment]
Hi, I met the same problem and fixed by using @unoriginalscreenname method. But I got another weird error, the running progress goes to another conda venv instead of sticking with the current venv (_learn-langchain_). Not sure why but I did cloned the previous venv to get _learn-langchain_. Thus I **removed this cloned venv** and installed conda venv from the beginning. This **issue is gone**. Hope this fix someone's issues. BR/sunny
